### PR TITLE
Adds support for user account authentication.

### PR DESCRIPTION
**Pull request by jneem**
This was added in a newer version of `yup-oauth`, so I've had to bump that. But not all the way to the latest version, because that has various other API breakages. I'd be happy to do that in a separate PR, if desired.

### CODE REVIEW

**Comment by rnarubin** [comment]
Nice. The latest yup-oauth could be useful because they added support also for instance metadata credentials. But i agree that such a change doesn't have to be in this PR.

**Comment by rnarubin** [comment]
A fix to the failing CI is in https://github.com/standard-ai/ya-gcp/pull/11

If you rebase they should pass I think

**Comment by jneem** [comment]
Hmm, it looks like I already have that commit... I think the bumped `yup-oauth2` pulls in a new version of `time` which has a higher MSRV

**Comment by rnarubin** [comment]
oh i see. Yeah I guess this a losing battle and ya-gcp needs to bump MSRV to 1.56 at least.

I can open a PR to do that, but I probably won't get to it until the end of this week. If you're on a shorter timeline then a PR is welcome.

**Pull request merged**
